name: Package

on: workflow_dispatch

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              pyinstaller main.py -F -w -n "CustomKnight Creator" -i resources/SheoIcon.icns --add-data resources:resources &&
              cd dist/ &&
              zip -r9 "CustomKnight Creator" "CustomKnight Creator.app/"
            OUT_FILE_PATH: "dist/CustomKnight Creator.zip"
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
              pyinstaller main.py -F -w -n "CustomKnight Creator" -i resources/SheoIcon.ico --add-data "resources;resources"
            OUT_FILE_PATH: "dist/CustomKnight Creator.exe"
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: >
              pyinstaller main.py -F -n "CustomKnight Creator" --add-data "resources:resources"
            OUT_FILE_PATH: "dist/CustomKnight Creator"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Pillow --no-binary :all:
        python -m pip install -r requirements.txt
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{matrix.TARGET}}
        path: ${{matrix.OUT_FILE_PATH}}
